//! Emit reference colour-surface samples as JSON.
//!
//! The editor UI reimplements Oklab and the keyframe surface in TypeScript so it
//! can preview the strip without a round trip. That is only useful if the two
//! implementations agree to the last byte, and nothing about the languages
//! enforces that.
//!
//! So this dumps what the Rust produces, the output is committed as
//! `ui/src/color/reference.json`, and tests on *both* sides assert against it.
//! Either implementation drifting breaks a test rather than quietly making the
//! editor lie.
//!
//! Two palettes are emitted. The first is the shipped default, which is fully
//! opaque and so pins the colour pipeline. The second is deliberately
//! translucent: opacity-weighted blending is the subtlest thing here to port,
//! and an all-opaque fixture would agree perfectly while both sides got it
//! wrong.
//!
//! Regenerate after any deliberate change to the colour pipeline:
//!
//! ```text
//! cargo run --example color_reference > ../ui/src/color/reference.json
//! ```

use djled_engine::color::oklab::{LinearRgb, Oklab};
use djled_engine::color::{ColorSurface, Keyframe, SurfaceConfig};

fn main() {
    println!("{{");
    println!("  \"note\": \"generated by `cargo run --example color_reference`; do not hand-edit\",");
    println!("  \"cases\": [");
    let cases = [
        ("default", SurfaceConfig::default()),
        ("translucent", translucent()),
    ];
    let rendered: Vec<String> = cases.iter().map(|(name, cfg)| case(name, cfg)).collect();
    println!("{}", rendered.join(",\n"));
    println!("  ]");
    println!("}}");
}

/// A palette spanning the opacity range, including a fully transparent keyframe
/// — the case where colour has to be dropped rather than averaged.
fn translucent() -> SurfaceConfig {
    SurfaceConfig {
        keyframes: vec![
            Keyframe::new(0.0, 0.0, "#ff200000"),
            Keyframe::new(0.0, 1.0, "#ff2000ff"),
            Keyframe::new(0.5, 0.5, "#40ff6080"),
            Keyframe::new(1.0, 0.0, "#00082040"),
            Keyframe::new(1.0, 1.0, "#40c0ffc0"),
        ],
        sigma: 0.3,
    }
}

fn case(name: &str, cfg: &SurfaceConfig) -> String {
    let surface = ColorSurface::new(cfg).expect("reference surface must be valid");

    let keyframes: Vec<String> = cfg
        .keyframes
        .iter()
        .map(|k| format!("        {{ \"x\": {}, \"y\": {}, \"color\": \"{}\" }}", k.x, k.y, k.color))
        .collect();

    let mut samples = Vec::new();
    for i in 0..=8 {
        for j in 0..=8 {
            let (x, y) = (i as f32 / 8.0, j as f32 / 8.0);
            let lab = surface.sample(x, y);
            let led = led_bytes(lab);
            samples.push(format!(
                "        {{ \"x\": {x}, \"y\": {y}, \
                 \"l\": {}, \"a\": {}, \"b\": {}, \"alpha\": {}, \
                 \"led\": [{}, {}, {}] }}",
                fmt(lab.l),
                fmt(lab.a),
                fmt(lab.b),
                fmt(lab.alpha),
                led[0],
                led[1],
                led[2],
            ));
        }
    }

    let lines = [
        "    {".to_string(),
        format!("      \"name\": \"{name}\","),
        format!("      \"sigma\": {},", cfg.sigma),
        "      \"keyframes\": [".to_string(),
        keyframes.join(",\n"),
        "      ],".to_string(),
        "      \"samples\": [".to_string(),
        samples.join(",\n"),
        "      ]".to_string(),
        "    }".to_string(),
    ];
    lines.join("\n")
}

/// Enough digits to pin f32 exactly, without trailing noise.
fn fmt(v: f32) -> String {
    format!("{v:.9}")
}

/// The bytes the firmware would receive: linear light, composited onto the unlit
/// strip, no sRGB encode.
fn led_bytes(lab: Oklab) -> [u8; 3] {
    let rgb = lab.to_linear_rgb().clamped().over(LinearRgb::BLACK);
    [
        (rgb.r * 255.0).round() as u8,
        (rgb.g * 255.0).round() as u8,
        (rgb.b * 255.0).round() as u8,
    ]
}
