//! Emit reference colour-surface samples as JSON.
//!
//! The editor UI reimplements Oklab and the keyframe surface in TypeScript so it
//! can preview the strip without a round trip. That is only useful if the two
//! implementations agree to the last byte, and nothing about the languages
//! enforces that.
//!
//! So this dumps what the Rust produces, the output is committed as
//! `ui/src/color/reference.json`, and tests on *both* sides assert against it.
//! Either implementation drifting breaks a test rather than quietly making the
//! editor lie.
//!
//! Regenerate after any deliberate change to the colour pipeline:
//!
//! ```text
//! cargo run --example color_reference > ../ui/src/color/reference.json
//! ```

use djled_engine::color::oklab::Oklab;
use djled_engine::color::{ColorSurface, SurfaceConfig};

fn main() {
    let cfg = SurfaceConfig::default();
    let surface = ColorSurface::new(&cfg).expect("default surface must be valid");

    let mut samples = Vec::new();
    for i in 0..=8 {
        for j in 0..=8 {
            let (x, y) = (i as f32 / 8.0, j as f32 / 8.0);
            let lab = surface.sample(x, y);
            samples.push(format!(
                "    {{ \"x\": {x}, \"y\": {y}, \"l\": {}, \"a\": {}, \"b\": {}, \"led\": [{}] }}",
                fmt(lab.l),
                fmt(lab.a),
                fmt(lab.b),
                led_bytes(lab)
                    .iter()
                    .map(|v| v.to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }

    println!("{{");
    println!("  \"note\": \"generated by `cargo run --example color_reference`; do not hand-edit\",");
    println!("  \"sigma\": {},", cfg.sigma);
    println!("  \"keyframes\": [");
    let keyframes: Vec<String> = cfg
        .keyframes
        .iter()
        .map(|k| format!("    {{ \"x\": {}, \"y\": {}, \"color\": \"{}\" }}", k.x, k.y, k.color))
        .collect();
    println!("{}", keyframes.join(",\n"));
    println!("  ],");
    println!("  \"samples\": [");
    println!("{}", samples.join(",\n"));
    println!("  ]");
    println!("}}");
}

/// Enough digits to pin f32 exactly, without trailing noise.
fn fmt(v: f32) -> String {
    format!("{v:.9}")
}

/// The bytes the firmware would receive: linear light, no sRGB encode.
fn led_bytes(lab: Oklab) -> [u8; 3] {
    let rgb = lab.to_linear_rgb().clamped();
    [
        (rgb.r * 255.0).round() as u8,
        (rgb.g * 255.0).round() as u8,
        (rgb.b * 255.0).round() as u8,
    ]
}
